export type PdfDocStatus = "READY" | "PDF_PENDING" | "INTERNAL_ONLY";

export interface PdfDocumentRecord {
  readonly id: string;
  readonly title: string;
  readonly subtitle: string;
  readonly audience: string;
  readonly category:
    | "Core Platform"
    | "Onboarding / KYC"
    | "RWA / Asset Packages"
    | "Funding Routes"
    | "XRPL / IOU / Wallets"
    | "Legacy / Buyback / LP Review"
    | "PATE-COAL-001";
  readonly description: string;
  readonly pdfPath: string;
  readonly version: string;
  readonly status: PdfDocStatus;
  readonly relatedRoutes: readonly string[];
  readonly requiredFor: readonly string[];
  readonly jsonExportAvailable: boolean;
  readonly primaryCtaLabel: "Download PDF";
  readonly secondaryCtaLabel?: "Technical JSON";
  readonly safetyNote?: string;
}

const SAFETY =
  "TROPTIONS materials are provided for informational and due-diligence purposes only. TROPTIONS is not a bank, broker-dealer, exchange, custodian, licensed financial institution, investment adviser, or legal adviser. No live custody, exchange, stablecoin issuance, IOU issuance, Aave execution, token buyback, liquidity pool execution, mining operation, or public investment functionality is enabled. All execution requires legal, compliance, provider, custody, signer, and governance approvals.";

export const PDF_DOCUMENT_REGISTRY: readonly PdfDocumentRecord[] = [
  {
    id: "troptions-platform-overview",
    title: "TROPTIONS Platform Overview",
    subtitle: "Architecture, Compliance & Participant Guide",
    audience: "All participants, lenders, partners",
    category: "Core Platform",
    description:
      "High-level overview of the TROPTIONS ecosystem: Layer 1 architecture, token supply, compliance framework, brand entities, participant roles, and governance model.",
    pdfPath: "/troptions/downloads/troptions-platform-overview.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions", "/troptions/layer1", "/troptions/ecosystem"],
    requiredFor: ["Initial onboarding review", "Lender due diligence", "Partner intake"],
    jsonExportAvailable: true,
    primaryCtaLabel: "Download PDF",
    secondaryCtaLabel: "Technical JSON",
    safetyNote: SAFETY,
  },
  {
    id: "kyc-onboarding-handbook",
    title: "KYC / Onboarding Handbook",
    subtitle: "Identity Verification, Document Submission & DID",
    audience: "Participants, operators, asset owners",
    category: "Onboarding / KYC",
    description:
      "Step-by-step onboarding guide: required documents, document hash submission, KYC tier levels, oracle attestation, and DID anchoring on XRPL.",
    pdfPath: "/troptions/downloads/kyc-onboarding-handbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/kyc", "/troptions/onboarding"],
    requiredFor: ["Participant onboarding", "Operator clearance", "Asset owner intake"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "rwa-tokenisation-handbook",
    title: "RWA Tokenisation Handbook",
    subtitle: "Gemstones, Real Estate, Equipment & More",
    audience: "Asset owners, attorneys, lenders",
    category: "RWA / Asset Packages",
    description:
      "Complete reference for real-world asset tokenisation: asset eligibility, custody requirements, SPV structure, due diligence process, and approval gates.",
    pdfPath: "/troptions/downloads/rwa-tokenisation-handbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/rwa", "/troptions/rwa/axl-001"],
    requiredFor: ["RWA intake", "Asset tokenisation approval", "Lender RWA review"],
    jsonExportAvailable: true,
    primaryCtaLabel: "Download PDF",
    secondaryCtaLabel: "Technical JSON",
    safetyNote: SAFETY,
  },
  {
    id: "carbon-credit-handbook",
    title: "Carbon Credit Handbook",
    subtitle: "Sale, Retirement & Registry Procedures",
    audience: "Carbon market participants, compliance officers",
    category: "RWA / Asset Packages",
    description:
      "Procedures for carbon credit sale and permanent retirement on Verra VCS, Gold Standard, ACR, or equivalent registries with full audit trail.",
    pdfPath: "/troptions/downloads/carbon-credit-handbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/carbon", "/troptions/transactions"],
    requiredFor: ["Carbon credit transaction approval", "Registry retirement"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "bitcoin-settlement-handbook",
    title: "Bitcoin Settlement Handbook",
    subtitle: "VASP Procedures, Travel Rule & Compliance",
    audience: "Settlement desks, compliance officers, lenders",
    category: "Funding Routes",
    description:
      "Reference for Bitcoin settlement preferences: VASP selection, wallet screening, Travel Rule compliance (≥$1,000), and source-of-funds requirements.",
    pdfPath: "/troptions/downloads/bitcoin-settlement-handbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/settlement", "/troptions/payment-rails"],
    requiredFor: ["BTC settlement approval", "VASP compliance"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "xrpl-iou-issuance-handbook",
    title: "XRPL IOU Issuance Handbook",
    subtitle: "Trustlines, Gateways & Compliance",
    audience: "Web3 operators, XRPL participants, compliance teams",
    category: "XRPL / IOU / Wallets",
    description:
      "Complete guide to XRPL IOU issuance via the TROPTIONS gateway: trustline setup, transfer fees, KYC requirements, and compliance controls. All issuance is gated and simulation-only until approvals complete.",
    pdfPath: "/troptions/downloads/xrpl-iou-issuance-handbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/xrpl-iou", "/troptions/xrpl-platform", "/troptions/stablecoins"],
    requiredFor: ["IOU issuance approval", "XRPL gateway onboarding"],
    jsonExportAvailable: true,
    primaryCtaLabel: "Download PDF",
    secondaryCtaLabel: "Technical JSON",
    safetyNote: SAFETY,
  },
  {
    id: "funding-routes-handbook",
    title: "Funding Routes Handbook",
    subtitle: "Route Selection, Requirements & Approval Gates",
    audience: "Asset owners, lenders, deal sponsors",
    category: "Funding Routes",
    description:
      "Detailed guide to all TROPTIONS funding routes: route eligibility matrix, document requirements, approval gates, lender scoring, and route verification procedures.",
    pdfPath: "/troptions/downloads/funding-routes-handbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/funding-routes", "/troptions/funding"],
    requiredFor: ["Funding route selection", "Lender submission"],
    jsonExportAvailable: true,
    primaryCtaLabel: "Download PDF",
    secondaryCtaLabel: "Technical JSON",
    safetyNote: SAFETY,
  },
  {
    id: "master-funding-playbook",
    title: "Master Funding Playbook",
    subtitle: "End-to-End Funding Process & Controls",
    audience: "Senior operators, deal principals, private credit desks",
    category: "Funding Routes",
    description:
      "Comprehensive playbook for TROPTIONS-assisted funding transactions: deal intake, asset review, route selection, document package, lender engagement, and closing controls.",
    pdfPath: "/troptions/downloads/master-funding-playbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/docs/funding-playbook", "/troptions/funding"],
    requiredFor: ["Deal principal review", "Private credit desk onboarding"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "funding-route-matrix",
    title: "Funding Route Matrix",
    subtitle: "Side-by-Side Route Comparison & Eligibility",
    audience: "Asset owners, lenders, deal analysts",
    category: "Funding Routes",
    description:
      "Quick-reference matrix comparing all TROPTIONS funding routes: minimum asset value, route type, typical timeline, required documents, approval authority, and current status.",
    pdfPath: "/troptions/downloads/funding-route-matrix.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/funding-routes"],
    requiredFor: ["Route selection analysis", "Lender pre-qualification"],
    jsonExportAvailable: true,
    primaryCtaLabel: "Download PDF",
    secondaryCtaLabel: "Technical JSON",
    safetyNote: SAFETY,
  },
  {
    id: "client-intake-document-checklist",
    title: "Client Intake Document Checklist",
    subtitle: "Master Document Request for All Asset Types",
    audience: "Asset owners, attorneys, deal coordinators",
    category: "Onboarding / KYC",
    description:
      "Master checklist covering all document categories required for TROPTIONS client intake: identity, entity, asset title, legal authority, financial, and compliance documents.",
    pdfPath: "/troptions/downloads/client-intake-document-checklist.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/kyc", "/troptions/onboarding"],
    requiredFor: ["All transaction onboarding", "Asset owner intake"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "pate-coal-001-funding-procedure",
    title: "PATE-COAL-001 Funding Procedure",
    subtitle: "Step-by-Step Funding Process for Pate Prospect",
    audience: "Asset owner, deal coordinator, lender",
    category: "PATE-COAL-001",
    description:
      "Step-by-step funding procedure for the Pate Prospect coal/mineral-rights RWA: current readiness score (40/100), hard blockers, required document sequence, approval gates, and route recommendations.",
    pdfPath: "/troptions/downloads/pate-coal-001-funding-procedure.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/rwa/pate-coal", "/troptions/funding-routes"],
    requiredFor: ["PATE-COAL-001 funding initiation"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "pate-coal-001-lender-review-packet",
    title: "PATE-COAL-001 Lender Review Packet",
    subtitle: "Executive Summary, Readiness Score & Financing Routes",
    audience: "Lenders, private credit desks, diligence teams",
    category: "PATE-COAL-001",
    description:
      "Comprehensive lender-facing overview of the Pate Prospect asset: uploaded evidence, 40/100 readiness score, 8 hard-blocker checklist, recommended routes, and Aave hard-block explanation.",
    pdfPath: "/troptions/downloads/pate-coal-001-lender-review-packet.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/rwa/pate-coal"],
    requiredFor: ["Lender initial review", "Private credit desk intake"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "pate-coal-001-owner-document-request",
    title: "PATE-COAL-001 Owner Document Request",
    subtitle: "Checklist: Title, Mineral Rights, Permits, Legal, Commercial",
    audience: "Asset owner, legal counsel",
    category: "PATE-COAL-001",
    description:
      "Formatted checklist for the PATE-COAL-001 asset owner covering all 9 document categories: title/deed, mineral rights, tax/lien/UCC, engineering, permitting/environmental, commercial/offtake, legal authority, funding terms, and XRPL receipt readiness.",
    pdfPath: "/troptions/downloads/pate-coal-001-owner-document-request.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/rwa/pate-coal"],
    requiredFor: ["Asset owner document submission"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "pate-coal-001-route-verification-guide",
    title: "PATE-COAL-001 Route Verification Guide",
    subtitle: "Deployment Checklist & Route Verification Procedures",
    audience: "Deal coordinators, technical operators",
    category: "PATE-COAL-001",
    description:
      "Post-deployment verification guide: all 5 PATE-COAL-001 routes, expected API responses, verification commands, and simulationOnly enforcement strings.",
    pdfPath: "/troptions/downloads/pate-coal-001-route-verification-guide.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/rwa/pate-coal"],
    requiredFor: ["Route deployment verification"],
    jsonExportAvailable: true,
    primaryCtaLabel: "Download PDF",
    secondaryCtaLabel: "Technical JSON",
    safetyNote: SAFETY,
  },
  {
    id: "axl-001-rwa-financing-checklist",
    title: "AXL-001 RWA Financing Checklist",
    subtitle: "Asset Financing Readiness & Due Diligence",
    audience: "Asset owners, lenders, compliance officers",
    category: "RWA / Asset Packages",
    description:
      "Complete financing checklist for the AXL-001 RWA package: asset verification, legal wrapper, custody confirmation, lender requirements, and approval conditions.",
    pdfPath: "/troptions/downloads/axl-001-rwa-financing-checklist.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/rwa/axl-001"],
    requiredFor: ["AXL-001 financing initiation", "Lender submission"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "legacy-token-migration-handbook",
    title: "Legacy Token Migration Handbook",
    subtitle: "Migration Procedures, Eligibility & Controls",
    audience: "Legacy token holders, compliance teams",
    category: "Legacy / Buyback / LP Review",
    description:
      "Guide to legacy TROPTIONS token migration: eligibility criteria, document requirements, migration workflow, approval gates, and what remains blocked pending legal and compliance review.",
    pdfPath: "/troptions/downloads/legacy-token-migration-handbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/migration", "/troptions/legacy"],
    requiredFor: ["Legacy token holder intake", "Migration approval"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "buyback-review-handbook",
    title: "Buyback Review Handbook",
    subtitle: "Token Buyback Readiness & Approval Gates",
    audience: "Token holders, governance participants",
    category: "Legacy / Buyback / LP Review",
    description:
      "Review handbook for TROPTIONS token buyback programs: readiness criteria, legal requirements, governance approval process, treasury controls, and what remains blocked until approvals complete.",
    pdfPath: "/troptions/downloads/buyback-review-handbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/treasury"],
    requiredFor: ["Buyback governance review"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "liquidity-pool-readiness-handbook",
    title: "Liquidity Pool Readiness Handbook",
    subtitle: "LP Setup, Compliance & Approval Requirements",
    audience: "DeFi operators, liquidity providers, compliance teams",
    category: "Legacy / Buyback / LP Review",
    description:
      "Readiness guide for TROPTIONS liquidity pool participation: legal entity requirements, KYC/AML controls, smart contract audit requirements, governance approval gates, and current status. All LP execution remains blocked pending approvals.",
    pdfPath: "/troptions/downloads/liquidity-pool-readiness-handbook.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/xchange"],
    requiredFor: ["LP participation approval"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "wallet-mint-noncustodial-guide",
    title: "Wallet Mint / Non-Custodial Wallet Guide",
    subtitle: "Wallet Setup, XRPL Trustlines & Non-Custodial Controls",
    audience: "Participants, operators, asset owners",
    category: "XRPL / IOU / Wallets",
    description:
      "Guide to TROPTIONS non-custodial wallet setup: XRPL wallet creation, trustline establishment, reserve requirements, security controls, and non-custodial usage. No custody or exchange functionality is enabled.",
    pdfPath: "/troptions/downloads/wallet-mint-noncustodial-guide.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/wallets", "/troptions/xrpl-platform"],
    requiredFor: ["Wallet onboarding", "XRPL participant setup"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "rust-runtime-control-layer-overview",
    title: "Rust Runtime / L1 Control Layer Overview",
    subtitle: "Layer 1 Architecture, Consensus & Governance",
    audience: "Technical operators, node operators, governance participants",
    category: "Core Platform",
    description:
      "Technical overview of the TROPTIONS Rust L1 control layer: crate architecture, consensus model, governance controls, bridge interfaces, and deployment requirements.",
    pdfPath: "/troptions/downloads/rust-runtime-control-layer-overview.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/layer1"],
    requiredFor: ["Node operator onboarding", "L1 governance participation"],
    jsonExportAvailable: true,
    primaryCtaLabel: "Download PDF",
    secondaryCtaLabel: "Technical JSON",
    safetyNote: SAFETY,
  },
  {
    id: "troptions-wallet-hub-guide",
    title: "TROPTIONS Wallet Hub Guide",
    subtitle: "Genesis / Treasury / x402 / Mesh / Pay Dashboard",
    audience: "Operators, treasury leads, compliance reviewers",
    category: "XRPL / IOU / Wallets",
    description:
      "Guide to the TROPTIONS Wallet Hub for viewing issuer, treasury, distribution, Stellar mirror, x402, and internal ledger balances with simulation-first transfer workflows.",
    pdfPath: "/troptions/downloads/troptions-wallet-hub-guide.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/wallet-hub", "/troptions/wallets"],
    requiredFor: ["Wallet operations review", "Treasury rail visibility"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "troptions-wallet-transfer-procedure",
    title: "TROPTIONS Wallet Transfer Procedure",
    subtitle: "Simulation-First, Approval-Gated Transfer Control",
    audience: "Operators, legal, compliance",
    category: "XRPL / IOU / Wallets",
    description:
      "Transfer intent lifecycle and controls for TROPTIONS wallet operations, including simulation, compliance review, approval requests, and gated live-send policy.",
    pdfPath: "/troptions/downloads/troptions-wallet-transfer-procedure.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/wallet-hub"],
    requiredFor: ["Transfer approval workflow", "Operator runbook"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "investment-property-acquisition-playbook",
    title: "Investment Property Acquisition Playbook",
    subtitle: "Property Lock, Hotels, Multifamily, and Deal Execution Flow",
    audience: "Brokers, owners, project sponsors, and client advisors",
    category: "Funding Routes",
    description:
      "Step-by-step operational playbook for locking and executing investment property and hotel deals with TROPTIONS settlement orchestration and approval gates.",
    pdfPath: "/troptions/downloads/investment-property-acquisition-playbook.pdf",
    version: "v1.0 · 2026-04-29",
    status: "READY",
    relatedRoutes: ["/troptions/funding-routes", "/troptions/funding"],
    requiredFor: ["Property lock workflow", "Hotel and multifamily acquisition process"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "proof-of-funds-package-template",
    title: "Proof of Funds Package Template",
    subtitle: "Professional POF Format for Properties, Hotels, and Portfolio Deals",
    audience: "Client advisors, brokers, owners, and acquisition desks",
    category: "Funding Routes",
    description:
      "Client-ready proof-of-funds package format with required fields, support evidence checklist, release controls, and no-overpromise language.",
    pdfPath: "/troptions/downloads/proof-of-funds-package-template.pdf",
    version: "v1.0 · 2026-04-29",
    status: "READY",
    relatedRoutes: ["/troptions/funding-routes", "/troptions/docs/funding-playbook"],
    requiredFor: ["Broker/seller POF submissions", "Funding credibility packet"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "usdc-usdt-vault-attestation-framework",
    title: "USDC/USDT Vault Attestation Framework",
    subtitle: "Locked Treasury Structure with Third-Party Verification and Chainlink Monitoring",
    audience: "Institutional counterparties, lenders, auditors, and escrow desks",
    category: "Funding Routes",
    description:
      "Institutional framework for proving USDC/USDT treasury balances while assets remain locked, including signer controls, verifier packet structure, and Chainlink-based monitoring guidance.",
    pdfPath: "/troptions/downloads/usdc-usdt-vault-attestation-framework.pdf",
    version: "v1.0 · 2026-04-29",
    status: "READY",
    relatedRoutes: ["/troptions/verification", "/troptions/stablecoins", "/troptions/wallet-hub"],
    requiredFor: ["Capital raise diligence", "Counterparty wallet verification", "Locked treasury attestations"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "private-placement-owner-strategy-brief",
    title: "Private Placement Owner Strategy Brief",
    subtitle: "Senior-Level Governance, Structure, and Control Design",
    audience: "Owners, principals, board-level stakeholders, and treasury governance leads",
    category: "Funding Routes",
    description:
      "Executive owner brief for private placement design, including governance controls, verifier program architecture, lock policy boundaries, and institutional diligence sequencing.",
    pdfPath: "/troptions/downloads/private-placement-owner-strategy-brief.pdf",
    version: "v1.0 · 2026-04-29",
    status: "READY",
    relatedRoutes: ["/troptions/funding-routes", "/troptions/verification", "/troptions/stablecoins"],
    requiredFor: ["Owner governance approvals", "Private placement architecture review"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "private-placement-sales-execution-guide",
    title: "Private Placement Sales Execution Guide",
    subtitle: "How to Present Locked Treasury Evidence to Qualified Counterparties",
    audience: "Capital introduction teams, placement agents, and relationship managers",
    category: "Funding Routes",
    description:
      "Sales-facing private placement guide covering qualification, packet delivery discipline, verifier handoff workflow, and disclosure-safe communication boundaries.",
    pdfPath: "/troptions/downloads/private-placement-sales-execution-guide.pdf",
    version: "v1.0 · 2026-04-29",
    status: "READY",
    relatedRoutes: ["/troptions/funding-routes", "/troptions/funding", "/troptions/verification"],
    requiredFor: ["Sales team readiness", "Counterparty packet delivery workflow"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "private-placement-minting-leverage-framework",
    title: "Private Placement Minting and Leverage Control Framework",
    subtitle: "Collateral Issuance, Treasury Leverage, and Risk Policy",
    audience: "Treasury leads, risk officers, compliance, and leverage governance teams",
    category: "Funding Routes",
    description:
      "Risk-focused framework for minting, leverage mechanics, LTV thresholds, auto-deleveraging controls, and governance-approved margin policy tied to collateral proofs.",
    pdfPath: "/troptions/downloads/private-placement-minting-leverage-framework.pdf",
    version: "v1.0 · 2026-04-29",
    status: "READY",
    relatedRoutes: ["/troptions/funding-routes", "/troptions/verification", "/troptions/risk"],
    requiredFor: ["Leverage governance", "Minting policy approval", "Risk threshold management"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "bryan-stone-kyc-cis-master-file",
    title: "Bryan Stone KYC/CIS Master File",
    subtitle: "Institutional Client Identification and Governance-Controlled Onboarding",
    audience: "Owner office, compliance team, legal counsel, and institutional diligence desks",
    category: "Onboarding / KYC",
    description:
      "Owner-level KYC/CIS master file for Bryan Stone and TROPTIONS with authority-chain mapping, screening controls, and controlled packet release standards.",
    pdfPath: "/troptions/downloads/bryan-stone-kyc-cis-master-file.pdf",
    version: "v1.0 · 2026-04-29",
    status: "READY",
    relatedRoutes: ["/troptions/kyc", "/troptions/verification", "/troptions/funding-routes"],
    requiredFor: ["Owner KYC/CIS institutional diligence", "Authority-chain validation"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "usdt-proof-of-funds-verification-and-validation",
    title: "USDT Proof of Funds Verification and Validation",
    subtitle: "Institutional Balance Validation, Wallet Control, and Counterparty Check Protocol",
    audience: "Traders, counterparties, lenders, compliance, and escrow verification teams",
    category: "Funding Routes",
    description:
      "Institutional USDT PoF protocol covering signed wallet-control checks, balance snapshot verification, counterparty reproducibility, and validation expiry controls.",
    pdfPath: "/troptions/downloads/usdt-proof-of-funds-verification-and-validation.pdf",
    version: "v1.0 · 2026-04-29",
    status: "READY",
    relatedRoutes: ["/troptions/verification", "/troptions/stablecoins", "/troptions/funding"],
    requiredFor: ["USDT trader/lender funding verification", "Counterparty validation checks"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "trader-account-validation-and-lock-control-framework",
    title: "Trader Account Validation and Lock Control Framework",
    subtitle: "Validated-Then-Locked Account Lifecycle for Institutional Trading Readiness",
    audience: "Trading operations, compliance, risk, and treasury control teams",
    category: "Funding Routes",
    description:
      "Account lifecycle framework from validation to lock-controlled state, with state transitions, monitoring thresholds, and dual-control release governance.",
    pdfPath: "/troptions/downloads/trader-account-validation-and-lock-control-framework.pdf",
    version: "v1.0 · 2026-04-29",
    status: "READY",
    relatedRoutes: ["/troptions/funding", "/troptions/verification", "/troptions/wallet-hub"],
    requiredFor: ["Trader readiness governance", "Validated-account lock policy implementation"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "broker-dealer-onboarding-and-xrpl-vaulting-framework",
    title: "Broker-Dealer Onboarding and XRPL Vaulting Framework",
    subtitle: "Institutional Integration Model for Broker-Dealer Controls and XRPL Vault Operations",
    audience: "Broker-dealer principals, legal/compliance teams, and institutional treasury operators",
    category: "XRPL / IOU / Wallets",
    description:
      "Blueprint for broker-dealer integration with TROPTIONS, including due diligence gates, supervisory model, and XRPL vault topology with segregation-of-duties.",
    pdfPath: "/troptions/downloads/broker-dealer-onboarding-and-xrpl-vaulting-framework.pdf",
    version: "v1.0 · 2026-04-29",
    status: "READY",
    relatedRoutes: ["/troptions/xrpl-platform", "/troptions/verification", "/troptions/funding-routes"],
    requiredFor: ["Broker-dealer integration planning", "XRPL institutional vault operating model"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "smart-contract-doc-onboarding-playbook",
    title: "Smart Contract and Document Onboarding Playbook",
    subtitle: "Simple Flow for Clients, Brokers, Owners, and Project Teams",
    audience: "Project teams, brokers, owners, legal/compliance coordinators",
    category: "Funding Routes",
    description:
      "Simple document-to-trigger onboarding flow for project deals, including milestone mapping, approval ownership, and settlement release controls.",
    pdfPath: "/troptions/downloads/smart-contract-doc-onboarding-playbook.pdf",
    version: "v1.0 · 2026-04-29",
    status: "READY",
    relatedRoutes: ["/troptions/funding", "/troptions/transactions"],
    requiredFor: ["Document onboarding workflow", "Trigger-based settlement planning"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "x402-mesh-pay-overview",
    title: "x402 Mesh Pay Overview",
    subtitle: "x402, Mesh, and Pay Rail Control Model",
    audience: "Payments and integration teams",
    category: "Funding Routes",
    description:
      "Operational overview of x402 credit rails, mesh payment concepts, and pay routing controls in TROPTIONS with simulation-only defaults.",
    pdfPath: "/troptions/downloads/x402-mesh-pay-overview.pdf",
    version: "v1.0 · 2026-04-28",
    status: "READY",
    relatedRoutes: ["/troptions/wallet-hub"],
    requiredFor: ["x402 integration review", "Rail governance review"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "bryan-stone-kyc-appendix-template",
    title: "Bryan Stone KYC Appendix Template",
    subtitle: "Redaction-Safe Field-Only Appendix for KYC Data Handling",
    audience: "Compliance coordinators, KYC analysts, and institutional administrators",
    category: "Onboarding / KYC",
    description:
      "Redaction-safe field-only appendix template for deriving and transmitting KYC fields from the Bryan Stone master file without exposing raw source documents.",
    pdfPath: "/troptions/downloads/bryan-stone-kyc-appendix-template.pdf",
    version: "v1.0 · 2026-04-29",
    status: "READY",
    relatedRoutes: ["/troptions/verification", "/troptions/downloads"],
    requiredFor: ["Bryan Stone KYC field transmission", "Redaction-safe compliance workflow"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "counterparty-verification-sheet",
    title: "Counterparty Verification Sheet",
    subtitle: "Fast One-Page Qualification and Verification Workflow for Traders and Counterparties",
    audience: "Compliance analysts, institutional intake coordinators, and trading operations teams",
    category: "Onboarding / KYC",
    description:
      "One-page rapid qualification gate covering trader identity, USDT verification, XRPL wallet check, account lock status, and compliance screening before any trade or onboarding commitment.",
    pdfPath: "/troptions/downloads/counterparty-verification-sheet.pdf",
    version: "v1.0 · 2026-04-29",
    status: "READY",
    relatedRoutes: ["/troptions/verification", "/troptions/funding"],
    requiredFor: ["Counterparty intake qualification", "Pre-trade compliance gate"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "broker-dealer-readiness-scorecard",
    title: "Broker-Dealer Readiness Scorecard",
    subtitle: "Scored Checklist for Onboarding Status, Compliance Gates, and XRPL Vault Readiness",
    audience: "TROPTIONS governance teams, broker-dealer principals, and compliance reviewers",
    category: "XRPL / IOU / Wallets",
    description:
      "Scored five-domain readiness checklist providing objective at-a-glance visibility into broker-dealer integration progress: licensing, KYC, XRPL vault, compliance approvals, and governance sign-off.",
    pdfPath: "/troptions/downloads/broker-dealer-readiness-scorecard.pdf",
    version: "v1.0 · 2026-04-29",
    status: "READY",
    relatedRoutes: ["/troptions/xrpl-platform", "/troptions/verification"],
    requiredFor: ["Broker-dealer activation threshold check", "Governance readiness reporting"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "capital-leverage-structuring-framework-50m",
    title: "$50M Capital Leverage Structuring Framework",
    subtitle: "Funding, Leverage, and Credit Expansion Paths for Institutional Deployment",
    audience: "Founders, treasury leads, private credit desks, and institutional counterparties",
    category: "Funding Routes",
    description:
      "Decision framework mapping how a verified $50M position can be routed into deployable financing via PoF anchoring, structured credit facilities, or collateral-of-record leverage lines.",
    pdfPath: "/troptions/downloads/capital-leverage-structuring-framework-50m.pdf",
    version: "v1.0 · 2026-04-29",
    status: "READY",
    relatedRoutes: ["/troptions/funding", "/troptions/verification", "/troptions/gated/downloads"],
    requiredFor: ["Institutional leverage route selection", "Funding committee package"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "xrpl-tx-cd7271274743c20635ed58515f84b399a4113fe40e62cfc8248446a494d1e642-xrpscan",
    title: "XRPL Transaction Evidence — CD7271...E642",
    subtitle: "XRPSCAN Transaction Hash Record for Verification Packet",
    audience: "Compliance reviewers, counterparties, auditors, and treasury verification teams",
    category: "XRPL / IOU / Wallets",
    description:
      "Primary XRPSCAN export for transaction hash CD7271274743C20635ED58515F84B399A4113FE40E62CFC8248446A494D1E642, retained as verification evidence.",
    pdfPath:
      "/troptions/downloads/xrpl-tx-cd7271274743c20635ed58515f84b399a4113fe40e62cfc8248446a494d1e642-xrpscan.pdf",
    version: "v1.0 · 2026-04-29",
    status: "READY",
    relatedRoutes: ["/troptions/verification", "/troptions/xrpl-platform", "/troptions/gated/downloads"],
    requiredFor: ["XRPL transaction proof attachment", "Institutional verification evidence"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
  {
    id: "xrpl-tx-b14c09d240af67279eec84e0cb521766df9bcfb909e1481486e62b928a528093-xrpscan",
    title: "XRPL Transaction Evidence — B14C09...8093",
    subtitle: "XRPSCAN Transaction Hash Record for Verification Packet",
    audience: "Compliance reviewers, counterparties, auditors, and treasury verification teams",
    category: "XRPL / IOU / Wallets",
    description:
      "Primary XRPSCAN export for transaction hash B14C09D240AF67279EEC84E0CB521766DF9BCFB909E1481486E62B928A528093, retained as verification evidence.",
    pdfPath:
      "/troptions/downloads/xrpl-tx-b14c09d240af67279eec84e0cb521766df9bcfb909e1481486e62b928a528093-xrpscan.pdf",
    version: "v1.0 · 2026-04-29",
    status: "READY",
    relatedRoutes: ["/troptions/verification", "/troptions/xrpl-platform", "/troptions/gated/downloads"],
    requiredFor: ["XRPL transaction proof attachment", "Institutional verification evidence"],
    jsonExportAvailable: false,
    primaryCtaLabel: "Download PDF",
    safetyNote: SAFETY,
  },
] as const;

export const PDF_SAFETY_DISCLAIMER =
  "TROPTIONS materials are provided for informational and due-diligence purposes only. TROPTIONS is not a bank, broker-dealer, exchange, custodian, licensed financial institution, investment adviser, or legal adviser. No live custody, exchange, stablecoin issuance, IOU issuance, Aave execution, token buyback, liquidity pool execution, mining operation, or public investment functionality is enabled. All execution requires legal, compliance, provider, custody, signer, and governance approvals.";

export const PDF_FILENAMES = [
  "troptions-platform-overview.pdf",
  "kyc-onboarding-handbook.pdf",
  "rwa-tokenisation-handbook.pdf",
  "carbon-credit-handbook.pdf",
  "bitcoin-settlement-handbook.pdf",
  "xrpl-iou-issuance-handbook.pdf",
  "funding-routes-handbook.pdf",
  "master-funding-playbook.pdf",
  "funding-route-matrix.pdf",
  "client-intake-document-checklist.pdf",
  "pate-coal-001-funding-procedure.pdf",
  "pate-coal-001-lender-review-packet.pdf",
  "pate-coal-001-owner-document-request.pdf",
  "pate-coal-001-route-verification-guide.pdf",
  "axl-001-rwa-financing-checklist.pdf",
  "legacy-token-migration-handbook.pdf",
  "buyback-review-handbook.pdf",
  "liquidity-pool-readiness-handbook.pdf",
  "wallet-mint-noncustodial-guide.pdf",
  "rust-runtime-control-layer-overview.pdf",
  "troptions-wallet-hub-guide.pdf",
  "troptions-wallet-transfer-procedure.pdf",
  "investment-property-acquisition-playbook.pdf",
  "proof-of-funds-package-template.pdf",
  "usdc-usdt-vault-attestation-framework.pdf",
  "private-placement-owner-strategy-brief.pdf",
  "private-placement-sales-execution-guide.pdf",
  "private-placement-minting-leverage-framework.pdf",
  "bryan-stone-kyc-cis-master-file.pdf",
  "usdt-proof-of-funds-verification-and-validation.pdf",
  "trader-account-validation-and-lock-control-framework.pdf",
  "broker-dealer-onboarding-and-xrpl-vaulting-framework.pdf",
  "smart-contract-doc-onboarding-playbook.pdf",
  "x402-mesh-pay-overview.pdf",
  "bryan-stone-kyc-appendix-template.pdf",
  "counterparty-verification-sheet.pdf",
  "broker-dealer-readiness-scorecard.pdf",
  "capital-leverage-structuring-framework-50m.pdf",
  "xrpl-tx-cd7271274743c20635ed58515f84b399a4113fe40e62cfc8248446a494d1e642-xrpscan.pdf",
  "xrpl-tx-b14c09d240af67279eec84e0cb521766df9bcfb909e1481486e62b928a528093-xrpscan.pdf",
] as const;
