// Fiat Rails PM2 Configuration v2.1 — agent orchestration + multi-x402 mesh

module.exports = {
  apps: [
    {
      name: 'payment-orchestrator',
      script: './orchestrator/index.js',
      cwd: __dirname,
      env: {
        NODE_ENV: 'production',
        PORT: 4022,
        COMPLIANCE_URL: 'http://localhost:4025',
        FEDWIRE_ADAPTER: 'http://localhost:4023',
        SWIFT_BRIDGE: 'http://localhost:4024',
        ISSUER_ADDRESS: 'rJLMSTy77hTxqgDw9WMxCnYC8m5vhqN3FQ',
        EXCHANGE_OS_URL: 'http://localhost:8091',
      },
      instances: 1,
      autorestart: true,
      max_memory_restart: '512M',
      log_file: './logs/orchestrator.log',
    },
    {
      name: 'fedwire-adapter',
      script: './fedwire-adapter/server.js',
      cwd: __dirname,
      env: { PORT: 4023, ORCHESTRATOR_URL: 'http://localhost:4022' },
      instances: 1,
      autorestart: true,
      max_memory_restart: '256M',
    },
    {
      name: 'swift-bridge',
      script: './swift-bridge/app.js',
      cwd: __dirname,
      env: { PORT: 4024, ORCHESTRATOR_URL: 'http://localhost:4022' },
      instances: 1,
      autorestart: true,
      max_memory_restart: '256M',
    },
    {
      name: 'compliance-engine',
      script: './compliance-engine/main.py',
      interpreter: 'python',
      cwd: __dirname,
      env: { PORT: 4025, PYTHONUNBUFFERED: '1' },
      instances: 1,
      autorestart: true,
      max_memory_restart: '256M',
    },
    {
      name: 'neobank-api',
      script: './neobank-api/server.js',
      cwd: __dirname,
      env: { PORT: 4026, ORCHESTRATOR_URL: 'http://localhost:4022' },
      instances: 1,
      autorestart: true,
      max_memory_restart: '256M',
    },
    {
      name: 'iou-reserve-monitor',
      script: './iou-reserve-monitor/monitor.js',
      cwd: __dirname,
      env: { PORT: 4027 },
      instances: 1,
      autorestart: true,
      max_memory_restart: '128M',
    },
    {
      name: 'arbitrage-bot',
      script: './arbitrage-bot/index.js',
      cwd: __dirname,
      env: {
        PORT: 4028,
        DRY_RUN: 'true',
        X402_GATEWAY_URL: 'http://localhost:4030',
        GATEWAY_URLS: 'http://localhost:4030,http://localhost:4034,http://localhost:4035',
        X402_US_URL: 'http://localhost:4030',
        X402_EU_URL: 'http://localhost:4034',
        X402_JP_URL: 'http://localhost:4035',
        ORCHESTRATOR_URL: 'http://localhost:4022',
        COMPLIANCE_URL: 'http://localhost:4025',
      },
      instances: 1,
      autorestart: true,
      max_memory_restart: '256M',
    },
    {
      name: 'baas-api',
      script: './baas-api/index.js',
      cwd: __dirname,
      env: {
        NODE_ENV: 'production',
        PORT: 4029,
        ORCHESTRATOR_URL: 'http://localhost:4022',
        X402_GATEWAY_URL: 'http://localhost:4030',
      },
      instances: 1,
      autorestart: true,
      max_memory_restart: '256M',
      log_file: './logs/baas-api.log',
    },
    {
      name: 'baas-dashboard',
      script: './baas-dashboard/server.js',
      cwd: __dirname,
      env: {
        PORT: 4040,
        BAAS_API_URL: 'http://localhost:4029',
        ORCHESTRATOR_URL: 'http://localhost:4022',
        EXCHANGE_OS_URL: 'http://localhost:8091',
      },
      instances: 1,
      autorestart: true,
      max_memory_restart: '256M',
    },
    {
      name: 'x402-gateway-v2',
      script: './x402-gateway/server.js',
      cwd: __dirname,
      env: {
        PORT: 4030,
        REGION: 'us',
        EXCHANGE_OS_URL: 'http://localhost:8091',
        NEOBANK_URL: 'http://localhost:4026',
        BAAS_URL: 'http://localhost:4029',
        COMPLIANCE_URL: 'http://localhost:4025',
      },
      instances: 1,
      autorestart: true,
      max_memory_restart: '256M',
    },
    {
      name: 'x402-gateway-eu',
      script: './x402-gateway-eu/server.js',
      cwd: __dirname,
      env: {
        PORT: 4034,
        REGION: 'eu',
        BASE_CURRENCY: 'EUR',
        EXCHANGE_OS_URL: 'http://localhost:8091',
        NEOBANK_URL: 'http://localhost:4026',
        BAAS_URL: 'http://localhost:4029',
        COMPLIANCE_URL: 'http://localhost:4025',
      },
      instances: 1,
      autorestart: true,
      max_memory_restart: '256M',
    },
    {
      name: 'x402-gateway-jp',
      script: './x402-gateway-jp/server.js',
      cwd: __dirname,
      env: {
        PORT: 4035,
        REGION: 'jp',
        BASE_CURRENCY: 'JPY',
        EXCHANGE_OS_URL: 'http://localhost:8091',
        NEOBANK_URL: 'http://localhost:4026',
        BAAS_URL: 'http://localhost:4029',
        COMPLIANCE_URL: 'http://localhost:4025',
      },
      instances: 1,
      autorestart: true,
      max_memory_restart: '256M',
    },
    {
      name: 'agent-orchestrator',
      script: './agent-orchestrator/server.js',
      cwd: __dirname,
      env: {
        PORT: 4031,
        DRY_RUN: 'true',
        MCP_URL: 'http://localhost:4731',
        ARBITRAGE_URL: 'http://localhost:4028',
        COMPLIANCE_URL: 'http://localhost:4025',
        X402_GATEWAY_URL: 'http://localhost:4030',
        X402_US_URL: 'http://localhost:4030',
        X402_EU_URL: 'http://localhost:4034',
        X402_JP_URL: 'http://localhost:4035',
        ORCHESTRATOR_URL: 'http://localhost:4022',
        BAAS_API_URL: 'http://localhost:4029',
      },
      instances: 1,
      autorestart: true,
      max_memory_restart: '256M',
      log_file: './logs/agent-orchestrator.log',
    },
  ],
};
