// TROPTIONS Exchange OS — Proof Packet Creator

import { xrplConfig } from "@/config/exchange-os/xrpl";
import { x402Config } from "@/config/exchange-os/x402";
import { features } from "@/config/exchange-os/features";
import type { ProofPacket, ProofPacketInput } from "./types";
import { randomUUID } from "crypto";

export function createProofPacket(input: ProofPacketInput): ProofPacket {
  return {
    id: randomUUID(),
    generatedAt: new Date().toISOString(),
    token: {
      name: input.tokenName,
      ticker: input.tokenTicker,
      issuer: input.issuerAddress,
      metadataUrl: input.metadataUrl,
    },
    network: {
      name: xrplConfig.network,
      websocket: xrplConfig.websocketUrl,
      mainnetEnabled: xrplConfig.mainnetEnabled,
      explorerBase: xrplConfig.explorerBase,
    },
    trustlineRequired: input.trustlineRequired ?? true,
    ammPool: input.ammPoolAccount
      ? { account: input.ammPoolAccount }
      : undefined,
    x402Services: input.x402ServiceIds ?? [],
    rewardPolicy: input.rewardPolicy ?? {},
    feePolicy: input.feePolicy ?? {},
    riskLabels: input.riskLabelIds ?? [],
    demoMode: features.demoMode,
    productionVerified:
      !features.demoMode &&
      xrplConfig.mainnetEnabled &&
      x402Config.enabled,
    attestation:
      "This proof packet was generated by TROPTIONS Exchange OS. " +
      "It does not constitute a legal guarantee, audit certificate, or investment advice. " +
      "Verify all claims independently.",
  };
}
