// TROPTIONS Exchange OS — Reward Policy Definitions

import { defaultFeePolicy } from "@/config/exchange-os/fees";
import type { RewardPolicy } from "./types";

export const REWARD_POLICIES: RewardPolicy[] = [
  {
    category: "creator",
    label: "Creator Rewards",
    description:
      "Token creators may earn a share of eligible platform fees generated by trading volume attributed to their token.",
    rewardBps: defaultFeePolicy.creatorRewardBps,
    enabled: true,
    disclaimers: [
      "Creator rewards are subject to real platform usage and program rules.",
      "Not all token volume is eligible. See terms for attribution rules.",
      "Rewards are not guaranteed. Nothing is financial advice.",
    ],
  },
  {
    category: "referral",
    label: "Referral Rewards",
    description:
      "Participants who refer new token creators, sponsors, or traders may earn eligible referral rewards.",
    rewardBps: defaultFeePolicy.referralRewardBps,
    enabled: true,
    disclaimers: [
      "Referral rewards require verified referral attribution.",
      "Subject to anti-abuse rules, minimum activity thresholds, and program terms.",
      "Not a guaranteed income stream.",
    ],
  },
  {
    category: "sponsor",
    label: "Sponsor Rewards",
    description:
      "Sponsors fund campaign reward pools. Users who complete qualifying actions may earn from sponsor pools.",
    rewardBps: defaultFeePolicy.sponsorRewardBps,
    enabled: true,
    disclaimers: [
      "Sponsor rewards depend on available campaign budget.",
      "Campaign terms set by each sponsor, not TROPTIONS.",
      "Past campaign performance does not guarantee future rewards.",
    ],
  },
  {
    category: "liquidity",
    label: "Liquidity Provider Rewards",
    description:
      "AMM liquidity providers may earn a share of trading fees from the pool they contribute to.",
    rewardBps: 3000, // 0.3% of AMM volume goes to LPs
    enabled: true,
    disclaimers: [
      "LP positions carry impermanent loss risk.",
      "Fee earnings depend on actual pool trading volume.",
      "Providing liquidity is not a guaranteed income strategy.",
      "You can lose value relative to holding the underlying assets.",
    ],
  },
  {
    category: "api-revenue",
    label: "Developer API Revenue",
    description:
      "Developers who build TROPTIONS-integrated services may share in x402 API revenue from their usage.",
    rewardBps: 2000,
    enabled: true,
    disclaimers: [
      "API revenue share requires an active developer agreement.",
      "Revenue depends on real API usage by your users.",
      "Not a guaranteed income.",
    ],
  },
  {
    category: "campaign",
    label: "Campaign Rewards",
    description:
      "Event city and merchant campaign participants may earn rewards for completing qualifying actions.",
    rewardBps: 0, // Varies per campaign
    enabled: true,
    disclaimers: [
      "Campaign rewards are set per campaign by the sponsoring operator.",
      "Subject to campaign budget and rules.",
      "Not guaranteed.",
    ],
  },
];

export function getPolicyByCategory(
  category: RewardPolicy["category"]
): RewardPolicy | undefined {
  return REWARD_POLICIES.find((p) => p.category === category);
}
