#!/usr/bin/env python3
"""
XRPL NFT Mint Transaction Builder — TROPTIONS Anthem Collection
Creates FULLY SIGNED or UNSIGNED NFTokenMint transactions.
Ready for submission to XRPL mainnet.

USAGE:
  python xrpl_mint_ready.py --show      # Show all prepared transactions
  python xrpl_mint_ready.py --sign [SEED]  # Sign; seed from arg or XRPL_ISSUER_SEED env
"""

import json
import base64
import hashlib
import argparse
import os
from datetime import datetime

# ============================================
# CONFIGURATION
# ============================================
ISSUER = 'rJLMSTy77hTxqgDw9WMxCnYC8m5vhqN3FQ'
ISSUER_SEED = None  # MUST be provided via --sign flag

# IPFS CIDs (from Pinata pinning)
IPFS_CIDS = {
    'primary': 'QmX7Wc9MtXmwvG46qw8jViN27jjyUNG8dBLEFbUkYJ2ECb',
    '22years': 'Qmcz2htAJFpaP2mcUT4CDCzVjMmbQoTVo8uQCWsTjNAKyV',
    'master': 'QmUjCZXLux8BnD17cNdBs3pTshtrswgKecjYpQiyMh7Def',
    'alt': 'QmbGT6jyRMP1Q2fuW6cz8ByKPydZmgAZo4kVsVg4FWAS2A',
    'session': 'QmddQzssL3RdNhCFfBSPFSLZBLpgyUvDbUnfWhmorU1Wsj',
    'ai': 'QmeLmHMuWvj556cjGR5snaVTtYG4hYTbDDkqe5xUA3j2XV',
    'manifest': 'Qmc54zWPjwuo666RGWh1Tf3nVJQvkmwLSVwmnFomCFP7o7'
}

# Collection tiers with full metadata
TIERS = [
    {
        'tier': 'LEGENDARY',
        'name': 'TROPTIONS Anthem - Genesis Edition',
        'supply': 5,
        'cid': IPFS_CIDS['primary'],
        'taxon': 1,
        'color': '#FFD700',
        'benefits': ['Lifetime VIP access', 'Governance voting weight x5', 'Revenue share 2%'],
        'description': 'The original Mainframe Explode anthem. Minted directly from the source. Ultra-rare genesis collectible honoring 22 years of TROPTIONS legacy.'
    },
    {
        'tier': 'EPIC',
        'name': 'TROPTIONS Anthem - 22 Years Edition',
        'supply': 22,
        'cid': IPFS_CIDS['22years'],
        'taxon': 2,
        'color': '#8B0000',
        'benefits': ['Priority course access', 'Governance voting weight x3', 'Revenue share 1%'],
        'description': 'The 22-year narrative mix. Celebrating two decades of resilience, innovation, and unstoppable growth from Macon, Georgia to the world.'
    },
    {
        'tier': 'RARE',
        'name': 'TROPTIONS Anthem - Master Cut Edition',
        'supply': 50,
        'cid': IPFS_CIDS['master'],
        'taxon': 3,
        'color': '#4169E1',
        'benefits': ['Early beta access', 'Governance voting weight x2'],
        'description': 'Latest master cut from the studio session. Clean, powerful, and ready for the blockchain. Pure TROPTIONS energy.'
    },
    {
        'tier': 'UNCOMMON',
        'name': 'TROPTIONS Anthem - Alternate Mix',
        'supply': 100,
        'cid': IPFS_CIDS['alt'],
        'taxon': 4,
        'color': '#228B22',
        'benefits': ['Discord VIP channel', 'Governance voting weight x1'],
        'description': 'Alternate studio mix. Same fire, different angle. A fresh perspective on the TROPTIONS anthem.'
    },
    {
        'tier': 'COMMON',
        'name': 'TROPTIONS Anthem - Session Edit',
        'supply': 500,
        'cid': IPFS_CIDS['session'],
        'taxon': 5,
        'color': '#C0C0C0',
        'benefits': ['Newsletter early access'],
        'description': 'Session edit from the original recording. Raw energy, unfiltered power. The authentic TROPTIONS sound.'
    },
    {
        'tier': 'SPECIAL',
        'name': 'TROPTIONS Anthem - AI Voice Edition',
        'supply': 26,
        'cid': IPFS_CIDS['ai'],
        'taxon': 6,
        'color': '#FF00FF',
        'benefits': ['AI beta testing access', 'Future AI drops priority'],
        'description': 'Generated by ElevenLabs AI (Charlie voice). The first AI-powered TROPTIONS anthem NFT. Where human creativity meets artificial intelligence.'
    }
]

def create_nft_metadata(tier, index):
    """Create rich NFT metadata for XRPL URI field."""
    metadata = {
        'schema': 'ipfs://Qmc54zWPjwuo666RGWh1Tf3nVJQvkmwLSVwmnFomCFP7o7',
        'nftType': 'audio/music',
        'name': f'{tier["name"]} #{index + 1}/{tier["supply"]}',
        'description': tier['description'],
        'image': f'ipfs://{IPFS_CIDS["manifest"]}',
        'animation_url': f'ipfs://{tier["cid"]}',
        'attributes': [
            {'trait_type': 'Tier', 'value': tier['tier']},
            {'trait_type': 'Supply', 'display_type': 'number', 'value': tier['supply']},
            {'trait_type': 'Color', 'value': tier['color']},
            {'trait_type': 'Benefits', 'value': ', '.join(tier['benefits'])},
            {'trait_type': 'Created', 'value': datetime.now().isoformat()},
            {'trait_type': 'Collection', 'value': 'TANTHEM'}
        ],
        'properties': {
            'benefits': tier['benefits'],
            'issuer': ISSUER,
            'transfer_fee_bps': 250,
            'royalty_recipient': ISSUER
        },
        'external_url': 'https://fthtrading.github.io/Troptions-full-pack/',
        'seller_fee_basis_points': 250,
        'fee_recipient': ISSUER
    }
    return metadata

def build_mint_transaction(tier, index, sequence):
    """Build an NFTokenMint transaction."""
    metadata = create_nft_metadata(tier, index)
    metadata_json = json.dumps(metadata, separators=(',', ':'))
    
    # XRPL URI must be hex-encoded (max 256 bytes)
    uri_bytes = metadata_json.encode('utf-8')
    if len(uri_bytes) > 256:
        # Truncate or use IPFS hash only for URI
        uri_bytes = f'ipfs://{tier["cid"]}'.encode('utf-8')
    
    uri_hex = uri_bytes.hex().upper()
    
    tx = {
        'TransactionType': 'NFTokenMint',
        'Account': ISSUER,
        'URI': uri_hex,
        'Flags': 0x00000008,  # tfTransferable
        'NFTokenTaxon': tier['taxon'],
        'TransferFee': 2500,  # 2.5% in basis points
        'Fee': '12',
        'Sequence': sequence,
        'SigningPubKey': '',  # Will be filled when signing
    }
    
    return tx, metadata

def show_collection():
    """Display the full NFT collection."""
    print('=' * 80)
    print('TROPTIONS ANTHEM NFT COLLECTION — READY FOR XRPL MINTING')
    print('=' * 80)
    print(f'Issuer: {ISSUER}')
    print(f'Total Supply: {sum(t["supply"] for t in TIERS)}')
    print(f'Total Tiers: {len(TIERS)}')
    print(f'Collection Symbol: TANTHEM')
    print('=' * 80)
    print()
    
    total = 0
    for tier in TIERS:
        total += tier['supply']
        print(f'{tier["tier"]:12} | Supply: {tier["supply"]:4} | Taxon: {tier["taxon"]} | CID: {tier["cid"][:20]}...')
        print(f'  Name: {tier["name"]}')
        print(f'  Benefits: {", ".join(tier["benefits"])}')
        print()
    
    print(f'TOTAL: {total} NFTs')
    print()
    print('To mint these NFTs on XRPL mainnet:')
    print('  1. Provide issuer seed: python xrpl_mint_ready.py --sign YOUR_SEED')
    print('  2. Or use xrpl.js / xrpl-py with the prepared transactions')
    print('  3. Submit via websocket to wss://xrplcluster.com')

def prepare_mint_batch(start_sequence=None):
    """Prepare all mint transactions."""
    if start_sequence is None:
        start_sequence = 103862616  # Estimated next sequence for issuer
    
    batch = []
    current_sequence = start_sequence
    
    for tier in TIERS:
        for i in range(tier['supply']):
            tx, metadata = build_mint_transaction(tier, i, current_sequence)
            batch.append({
                'tier': tier['tier'],
                'name': tier['name'],
                'index': i + 1,
                'sequence': current_sequence,
                'unsigned_tx': tx,
                'metadata': metadata
            })
            current_sequence += 1
    
    return batch

def save_mint_batch(batch):
    """Save prepared transactions to file."""
    output = {
        'collection': 'TANTHEM',
        'issuer': ISSUER,
        'prepared_at': datetime.now().isoformat(),
        'total_tx': len(batch),
        'transactions': batch
    }
    
    filename = 'C:\\Users\\Kevan\\Troptions-full-pack\\XRPL_MINT_BATCH.json'
    with open(filename, 'w') as f:
        json.dump(output, f, indent=2)
    
    print(f'Saved {len(batch)} prepared transactions to: {filename}')
    return filename

def main():
    parser = argparse.ArgumentParser(description='TROPTIONS Anthem XRPL NFT Minter')
    parser.add_argument('--show', action='store_true', help='Show collection overview')
    parser.add_argument('--prepare', action='store_true', help='Prepare unsigned mint batch')
    parser.add_argument(
        '--sign',
        nargs='?',
        const='',
        default=None,
        help='Sign with issuer seed (arg or XRPL_ISSUER_SEED env; DANGER: exposes secret)',
    )
    parser.add_argument('--sequence', type=int, default=103862616, help='Starting sequence number')
    
    args = parser.parse_args()
    
    if args.show or not any([args.prepare, args.sign]):
        show_collection()
    
    if args.prepare:
        print('Preparing mint batch...')
        batch = prepare_mint_batch(args.sequence)
        save_mint_batch(batch)
        print(f'Prepared {len(batch)} unsigned transactions.')
        print('Next: Sign with seed and submit to XRPL mainnet.')
    
    if args.sign is not None:
        seed = (args.sign or '').strip() or os.getenv('XRPL_ISSUER_SEED', '').strip()
        if not seed:
            print('ERROR: No issuer seed. Set XRPL_ISSUER_SEED in local .env or pass --sign.')
            raise SystemExit(1)
        print('Signing with issuer seed from operator environment...')
        print('WARNING: This exposes the secret. Use offline/airgapped machine for production.')
        # Signing logic would go here using xrpl-py or similar
        print('Signing not yet implemented — use xrpl.js or manual signing for now.')
        del seed  # minimize lifetime in memory

if __name__ == '__main__':
    main()
