#!/usr/bin/env python3
"""
Create TROPTIONS Anthem NFTs on XRPL with rarity tiers.
Uses NFTokenMint transaction with IPFS CIDs as URI.
"""

import asyncio
import websockets
import json
import base64
from datetime import datetime

# XRPL Issuer (NFToken minter)
ISSUER = 'rJLMSTy77hTxqgDw9WMxCnYC8m5vhqN3FQ'

# IPFS CIDs from Pinata
IPFS_CIDS = {
    'troptions-theme-primary.mp3': 'QmX7Wc9MtXmwvG46qw8jViN27jjyUNG8dBLEFbUkYJ2ECb',
    'troptions-theme-alt.mp3': 'QmbGT6jyRMP1Q2fuW6cz8ByKPydZmgAZo4kVsVg4FWAS2A',
    'troptions-anthem-mainframe-152254.mp3': 'QmUjCZXLux8BnD17cNdBs3pTshtrswgKecjYpQiyMh7Def',
    'troptions-anthem-22-years.mp3': 'Qmcz2htAJFpaP2mcUT4CDCzVjMmbQoTVo8uQCWsTjNAKyV',
    'troptions-anthem-151853.mp3': 'QmddQzssL3RdNhCFfBSPFSLZBLpgyUvDbUnfWhmorU1Wsj',
    'troptions-anthem-elevenlabs-charlie.mp3': 'QmeLmHMuWvj556cjGR5snaVTtYG4hYTbDDkqe5xUA3j2XV',
    'manifest': 'Qmc54zWPjwuo666RGWh1Tf3nVJQvkmwLSVwmnFomCFP7o7'
}

# Rarity tiers for TROPTIONS Anthem NFTs
RARITY_TIERS = [
    {
        'tier': 'LEGENDARY',
        'name': 'TROPTIONS Anthem - Genesis Edition',
        'description': 'The original Mainframe Explode anthem. Minted directly from the source. Ultra-rare genesis collectible.',
        'track': 'troptions-theme-primary.mp3',
        'supply': 5,  # Only 5 exist
        'color': '#FFD700',  # Gold
        'benefits': ['Lifetime VIP access', 'Governance voting weight x5', 'Revenue share 2%']
    },
    {
        'tier': 'EPIC',
        'name': 'TROPTIONS Anthem - 22 Years Edition',
        'description': 'The 22-year narrative mix. Celebrating two decades of resilience and innovation.',
        'track': 'troptions-anthem-22-years.mp3',
        'supply': 22,  # 22 for 22 years
        'color': '#8B0000',  # Dark Red
        'benefits': ['Priority course access', 'Governance voting weight x3', 'Revenue share 1%']
    },
    {
        'tier': 'RARE',
        'name': 'TROPTIONS Anthem - Master Cut Edition',
        'description': 'Latest master cut from the studio session. Clean, powerful, ready for the chain.',
        'track': 'troptions-anthem-mainframe-152254.mp3',
        'supply': 50,
        'color': '#4169E1',  # Royal Blue
        'benefits': ['Early beta access', 'Governance voting weight x2']
    },
    {
        'tier': 'UNCOMMON',
        'name': 'TROPTIONS Anthem - Alternate Mix',
        'description': 'Alternate studio mix. Same fire, different angle.',
        'track': 'troptions-theme-alt.mp3',
        'supply': 100,
        'color': '#228B22',  # Forest Green
        'benefits': ['Discord VIP channel', 'Governance voting weight x1']
    },
    {
        'tier': 'COMMON',
        'name': 'TROPTIONS Anthem - Session Edit',
        'description': 'Session edit from the original recording. Raw energy.',
        'track': 'troptions-anthem-151853.mp3',
        'supply': 500,
        'color': '#C0C0C0',  # Silver
        'benefits': ['Newsletter early access']
    },
    {
        'tier': 'SPECIAL',
        'name': 'TROPTIONS Anthem - AI Voice Edition',
        'description': 'Generated by ElevenLabs AI (Charlie voice). The first AI-powered TROPTIONS anthem NFT.',
        'track': 'troptions-anthem-elevenlabs-charlie.mp3',
        'supply': 26,  # 26 = 2026
        'color': '#FF00FF',  # Magenta
        'benefits': ['AI beta testing access', 'Future AI drops priority']
    }
]

def create_nft_metadata(tier_info, cid):
    """Create NFT metadata JSON compatible with XRPL URI field."""
    metadata = {
        'name': tier_info['name'],
        'description': tier_info['description'],
        'image': f'ipfs://{IPFS_CIDS["manifest"]}',  # Manifest as cover
        'animation_url': f'ipfs://{cid}',  # The actual audio file
        'attributes': [
            {'trait_type': 'Tier', 'value': tier_info['tier']},
            {'trait_type': 'Supply', 'value': tier_info['supply']},
            {'trait_type': 'Color', 'value': tier_info['color']},
            {'trait_type': 'Track', 'value': tier_info['track']},
            {'trait_type': 'Created', 'value': datetime.now().isoformat()}
        ],
        'benefits': tier_info['benefits'],
        'external_url': 'https://fthtrading.github.io/Troptions-full-pack/',
        'seller_fee_basis_points': 250,  # 2.5% royalty
        'fee_recipient': 'rJLMSTy77hTxqgDw9WMxCnYC8m5vhqN3FQ'
    }
    return metadata

async def prepare_nft_batch():
    """Prepare NFT mint transactions (requires seed - we'll build unsigned transactions)."""
    print('=== TROPTIONS ANTHEM NFT RARITY SYSTEM ===')
    print(f'Issuer: {ISSUER}')
    print(f'Total Tiers: {len(RARITY_TIERS)}')
    total_supply = sum(t['supply'] for t in RARITY_TIERS)
    print(f'Total Supply: {total_supply}')
    print()
    
    nft_batch = []
    
    for tier in RARITY_TIERS:
        cid = IPFS_CIDS.get(tier['track'])
        if not cid:
            print(f'Warning: CID not found for {tier["track"]}')
            continue
        
        metadata = create_nft_metadata(tier, cid)
        
        # Convert metadata to base64 for URI field (XRPL requires base64 URI)
        metadata_json = json.dumps(metadata)
        uri_base64 = base64.b64encode(metadata_json.encode()).decode()
        
        # XRPL NFTokenMint structure (unsigned - needs seed to sign)
        nft_tx = {
            'TransactionType': 'NFTokenMint',
            'Account': ISSUER,
            'URI': uri_base64,
            'Flags': 8,  # tfTransferable - can be traded
            'NFTokenTaxon': 0,  # Collection identifier
            'TransferFee': 2500,  # 2.5% transfer fee (in basis points, max 50000 = 50%)
            'Amount': '0',  # Not an offer, just minting
            'Fee': '12',  # Minimum fee
            'Sequence': 'AUTO',  # Will be filled
        }
        
        nft_batch.append({
            'tier': tier['tier'],
            'name': tier['name'],
            'supply': tier['supply'],
            'cid': cid,
            'metadata': metadata,
            'uri_base64': uri_base64[:50] + '...',  # Truncated for display
            'unsigned_tx': nft_tx
        })
        
        tier_name = tier["tier"]
        tier_name_short = tier["name"][:40]
        supply = tier["supply"]
        cid_short = cid[:20]
        print(f'{tier_name:12} | {tier_name_short:40} | Supply: {supply:4} | CID: {cid_short}...')
    
    return nft_batch

def save_nft_manifest(batch):
    """Save the complete NFT manifest."""
    manifest = {
        'collection_name': 'TROPTIONS Anthem - Mainframe Explode',
        'collection_symbol': 'TANTHEM',
        'issuer': ISSUER,
        'created': datetime.now().isoformat(),
        'total_tiers': len(batch),
        'total_supply': sum(item['supply'] for item in batch),
        'ipfs_manifest': IPFS_CIDS['manifest'],
        'tiers': []
    }
    
    for item in batch:
        manifest['tiers'].append({
            'tier': item['tier'],
            'name': item['name'],
            'supply': item['supply'],
            'cid': item['cid'],
            'track': item['metadata']['attributes'][3]['value'],
            'benefits': item['metadata']['benefits'],
            'color': item['metadata']['attributes'][2]['value']
        })
    
    output_file = 'C:\\Users\\Kevan\\Troptions-full-pack\\TROPTIONS_NFT_RARITY_MANIFEST.json'
    with open(output_file, 'w') as f:
        json.dump(manifest, f, indent=2)
    
    print(f'\nSaved NFT manifest to: {output_file}')
    return manifest

if __name__ == '__main__':
    batch = asyncio.run(prepare_nft_batch())
    manifest = save_nft_manifest(batch)
    
    print('\n=== NFT RARITY SUMMARY ===')
    total = 0
    for tier in manifest['tiers']:
        tier_name = tier["tier"]
        supply = tier["supply"]
        name = tier["name"]
        print(f'  {tier_name:12} | {supply:4} supply | {name}')
        total += tier['supply']
    print(f'  {"TOTAL":12} | {total:4} NFTs')
    print('\nNote: These are prepared unsigned transactions.')
    print('To mint: Sign with issuer seed and submit to XRPL mainnet.')
