import type { ComplianceGate, NamespaceRecord, PartnerRecord, TroptionsGeniusProfile } from "@/lib/troptions/genius/types";
import { getNamespaceAllowedActions } from "@/lib/troptions/genius/namespace";

export const TROP_USD_SIM_TOKEN = {
  symbol: "TROP-USD-SIM",
  name: "Troptions USD Simulation Token",
  status: "sandbox_only" as const,
  liveIssuance: false,
};

export const GENIUS_PROFILE: TroptionsGeniusProfile = {
  programName: "Troptions Regulated Digital Settlement OS",
  issuerMode: "sandbox_simulation",
  issuanceStatus: "blocked_missing_regulator_approval",
  jurisdiction: "United States",
  creditUnionPartnerName: "Blue River Community Credit Union",
  cusoPartnerName: "Coastal Shared Services CUSO",
  ppsiPartnerName: "PPSI Diligence Candidate",
  reserveCustodianName: "Treasury Reserve Custody Candidate",
  kycKybProviderName: "Atlas Identity Mock",
  amlProviderName: "Signal AML Mock",
  chainNetworksAllowed: ["XRPL", "Stellar", "Ethereum L2", "Solana", "Private permissioned ledger", "Rust-native Troptions settlement ledger"],
  publicChainAllowed: true,
  liveActionsEnabled: false,
  legalCounselMemoApproved: false,
  regulatorApprovalRecorded: false,
  boardApprovalRecorded: false,
  reservePolicyApproved: true,
  reserveAttestationCurrent: false,
  redemptionPolicyApproved: true,
  amlSanctionsProgramApproved: true,
  kycKybProviderActive: true,
  incidentResponsePlanApproved: true,
  consumerDisclosuresApproved: false,
  chainRiskReviewApproved: false,
  smartContractAuditApproved: false,
};

export const GENIUS_GATES: ComplianceGate[] = [
  { id: "legal-counsel-memo", label: "Legal counsel memo", status: "review", requiredFor: "live", owner: "Legal" },
  { id: "board-approval", label: "Board approval", status: "draft", requiredFor: "live", owner: "Board" },
  { id: "regulator-approval", label: "Regulator approval", status: "missing", requiredFor: "live", owner: "Regulatory" },
  { id: "reserve-policy", label: "Reserve policy", status: "approved", requiredFor: "partner_ready", owner: "Treasury" },
  { id: "reserve-custody-agreement", label: "Reserve custody agreement", status: "review", requiredFor: "regulator_ready", owner: "Treasury" },
  { id: "reserve-attestation", label: "Reserve attestation", status: "expired", requiredFor: "live", owner: "Audit" },
  { id: "redemption-policy", label: "Redemption policy", status: "approved", requiredFor: "partner_ready", owner: "Operations" },
  { id: "aml-bsa-policy", label: "AML/BSA policy", status: "approved", requiredFor: "sandbox", owner: "Compliance" },
  { id: "sanctions-policy", label: "Sanctions/OFAC policy", status: "approved", requiredFor: "sandbox", owner: "Compliance" },
  { id: "kyc-kyb-provider", label: "KYC/KYB provider", status: "approved", requiredFor: "sandbox", owner: "Compliance" },
  { id: "chain-analytics-provider", label: "Chain analytics provider", status: "review", requiredFor: "live", owner: "Risk" },
  { id: "smart-contract-audit", label: "Smart contract audit", status: "missing", requiredFor: "live", owner: "Engineering" },
  { id: "cybersecurity-plan", label: "Cybersecurity plan", status: "review", requiredFor: "regulator_ready", owner: "Security" },
  { id: "incident-response-plan", label: "Incident response plan", status: "approved", requiredFor: "partner_ready", owner: "Security" },
  { id: "consumer-disclosures", label: "Consumer disclosures", status: "draft", requiredFor: "live", owner: "Legal" },
  { id: "marketing-review", label: "Marketing review", status: "review", requiredFor: "regulator_ready", owner: "Marketing" },
  { id: "rwa-securities-review", label: "RWA/securities review", status: "review", requiredFor: "regulator_ready", owner: "Legal" },
  { id: "tax-accounting-review", label: "Tax/accounting review", status: "draft", requiredFor: "partner_ready", owner: "Finance" },
];

export const PARTNER_REGISTRY: PartnerRecord[] = [
  {
    id: "partner-cu-001",
    category: "credit_union_partner",
    name: "Blue River Community Credit Union",
    readiness: "diligence",
    summary: "Member-owned institution with merchant pilot interest and existing KYC relationship depth.",
    allowedForResearch: true,
    allowedForSandbox: true,
    allowedForLive: false,
  },
  {
    id: "partner-cuso-001",
    category: "cuso_partner",
    name: "Coastal Shared Services CUSO",
    readiness: "candidate",
    summary: "Shared-services operating model for compliance, servicing, and integration support.",
    allowedForResearch: true,
    allowedForSandbox: true,
    allowedForLive: false,
  },
  {
    id: "partner-ppsi-001",
    category: "ppsi_partner",
    name: "PPSI Diligence Candidate",
    readiness: "candidate",
    summary: "Potential permitted payment stablecoin issuer partner for regulated issuance lane.",
    allowedForResearch: true,
    allowedForSandbox: true,
    allowedForLive: false,
  },
  {
    id: "partner-custody-001",
    category: "reserve_custodian",
    name: "Treasury Reserve Custody Candidate",
    readiness: "diligence",
    summary: "Reserve custody and attestation coordination partner candidate.",
    allowedForResearch: true,
    allowedForSandbox: true,
    allowedForLive: false,
  },
  {
    id: "partner-kyc-001",
    category: "kyc_kyb_provider",
    name: "Atlas Identity Mock",
    readiness: "approved",
    summary: "Sandbox KYC/KYB orchestration partner for namespace onboarding.",
    allowedForResearch: true,
    allowedForSandbox: true,
    allowedForLive: false,
  },
  {
    id: "partner-aml-001",
    category: "aml_sanctions_provider",
    name: "Signal AML Mock",
    readiness: "approved",
    summary: "Mock AML and sanctions screening orchestration provider for readiness evaluation.",
    allowedForResearch: true,
    allowedForSandbox: true,
    allowedForLive: false,
  },
  {
    id: "partner-chain-001",
    category: "chain_analytics_provider",
    name: "ChainScope Review Candidate",
    readiness: "diligence",
    summary: "Public-chain monitoring, travel-rule support, and anomaly review candidate.",
    allowedForResearch: true,
    allowedForSandbox: true,
    allowedForLive: false,
  },
  {
    id: "partner-legal-001",
    category: "legal_counsel",
    name: "Payments Counsel Mock",
    readiness: "diligence",
    summary: "Outside counsel path for GENIUS, NCUA, and tokenized-deposit legal review.",
    allowedForResearch: true,
    allowedForSandbox: true,
    allowedForLive: false,
  },
  {
    id: "partner-audit-001",
    category: "audit_attestation_provider",
    name: "Reserve Attestation Mock",
    readiness: "candidate",
    summary: "Monthly reserve attestation and controls evidence provider candidate.",
    allowedForResearch: true,
    allowedForSandbox: true,
    allowedForLive: false,
  },
  {
    id: "partner-cyber-001",
    category: "cybersecurity_provider",
    name: "Operational Resilience Mock",
    readiness: "approved",
    summary: "Cyber and incident response planning provider for sandbox and diligence lanes.",
    allowedForResearch: true,
    allowedForSandbox: true,
    allowedForLive: false,
  },
];

const BASE_NAMESPACES: NamespaceRecord[] = [
  {
    namespaceId: "member-001",
    displayName: "Member Alpha",
    namespaceType: "member",
    kycStatus: "mock_approved",
    kybStatus: "mock_approved",
    sanctionsStatus: "clear",
    walletStatus: "sandbox_enabled",
    settlementStatus: "simulation_only",
    allowedActions: [],
    blockedActions: [],
    evidenceLinks: ["docs/troptions/genius-stablecoin/exports/partner-readiness-packet.md"],
  },
  {
    namespaceId: "merchant-001",
    displayName: "Merchant Harbor",
    namespaceType: "merchant",
    kycStatus: "mock_approved",
    kybStatus: "mock_approved",
    sanctionsStatus: "clear",
    walletStatus: "sandbox_enabled",
    settlementStatus: "simulation_only",
    allowedActions: [],
    blockedActions: [],
    evidenceLinks: ["docs/troptions/genius-stablecoin/exports/merchant-settlement-packet.md"],
  },
  {
    namespaceId: "institution-001",
    displayName: "Institution Diligence Room",
    namespaceType: "institution",
    kycStatus: "mock_approved",
    kybStatus: "pending",
    sanctionsStatus: "review",
    walletStatus: "pending",
    settlementStatus: "live_locked",
    allowedActions: [],
    blockedActions: [],
    evidenceLinks: ["docs/troptions/genius-stablecoin/exports/regulator-readiness-packet.md"],
  },
  {
    namespaceId: "credit-union-001",
    displayName: "Blue River Community Credit Union",
    namespaceType: "credit_union",
    kycStatus: "mock_approved",
    kybStatus: "mock_approved",
    sanctionsStatus: "clear",
    walletStatus: "sandbox_enabled",
    settlementStatus: "partner_gated",
    allowedActions: [],
    blockedActions: [],
    evidenceLinks: ["docs/troptions/genius-stablecoin/README.md"],
  },
];

export const GENIUS_NAMESPACES: NamespaceRecord[] = BASE_NAMESPACES.map((namespace) => ({
  ...namespace,
  ...getNamespaceAllowedActions(namespace, GENIUS_PROFILE, GENIUS_GATES, [
    "simulate_mint",
    "simulate_burn",
    "simulate_transfer",
    "simulate_redemption_request",
    "live_mint",
    "live_burn",
    "live_redemption",
  ]),
}));