export interface EcosystemEvolutionItem {
  id: string;
  title: string;
  legacyDescription: string;
  institutionalRewrite: string;
  requiredEvidence: readonly string[];
  currentSystemModule: string;
  nextSteps: readonly string[];
  blockedConditions: readonly string[];
}

export const ECOSYSTEM_EVOLUTION_REGISTRY: readonly EcosystemEvolutionItem[] = [
  {
    id: "ECO-TPAY",
    title: "Troptions Pay",
    legacyDescription: "Legacy payment utility narrative tied to merchant acceptance and network reach messaging.",
    institutionalRewrite: "Payment narratives are converted into rail-evaluation records with provider dependencies and dated claim controls.",
    requiredEvidence: ["Provider relationship evidence", "Acceptance-condition matrix", "Dated source snapshots"],
    currentSystemModule: "payments-and-rail-evaluation",
    nextSteps: ["Reconcile merchant claims", "Attach provider confirmation", "Publish controlled language"],
    blockedConditions: ["No verified merchant-count evidence", "No provider/legal sign-off"],
  },
  {
    id: "ECO-UNITY",
    title: "Troptions Unity",
    legacyDescription: "Unity track presented as Solana utility with community and humanitarian narratives.",
    institutionalRewrite: "Unity claims are managed as source-tagged records requiring governance, legal classification, and impact evidence.",
    requiredEvidence: ["Token legal memo", "Governance disclosures", "Impact reporting method"],
    currentSystemModule: "claim-and-source-registry",
    nextSteps: ["Define approved institutional language", "Add impact evidence schema"],
    blockedConditions: ["No reserve/custody proof for backing claims", "No legal clearance"],
  },
  {
    id: "ECO-GOLD",
    title: "Troptions Gold",
    legacyDescription: "Gold and commodity narratives linked to reserve and value-positioning statements.",
    institutionalRewrite: "Gold assertions are routed through custody, valuation, legal, and accounting evidence workflows.",
    requiredEvidence: ["Custody records", "Valuation policy", "Accounting review"],
    currentSystemModule: "rwa-and-proof-workflows",
    nextSteps: ["Package evidence bundles", "Apply risk and legal review gates"],
    blockedConditions: ["No custody/provider approval", "No accounting treatment review"],
  },
  {
    id: "ECO-MERCHANT-RAILS",
    title: "Merchant/Payment Rails",
    legacyDescription: "Merchant-network reach statements spanning Troptions and adjacent payment references.",
    institutionalRewrite: "Merchant narratives are treated as claim records with verification status and blocked wording until evidence is attached.",
    requiredEvidence: ["Dated merchant dataset", "Provider attestation", "Coverage exclusions"],
    currentSystemModule: "legacy-claim-registry",
    nextSteps: ["Tag conflicting sources", "Publish verification state"],
    blockedConditions: ["Conflicting source counts", "Missing primary evidence"],
  },
  {
    id: "ECO-RWA-SALP",
    title: "RWA / SALP Concepts",
    legacyDescription: "Conceptual tokenization narratives for real assets and structured programs.",
    institutionalRewrite: "Concepts are translated into intake packages requiring title, valuation, legal, and custody controls.",
    requiredEvidence: ["Title and rights evidence", "Valuation packet", "Custody and legal classification"],
    currentSystemModule: "rwa-intake",
    nextSteps: ["Standardize intake checklists", "Map release gates"],
    blockedConditions: ["Incomplete intake package", "Missing legal or custody validation"],
  },
  {
    id: "ECO-GIVBUX",
    title: "GivBux Relationship",
    legacyDescription: "Third-party relationship appears in payment and merchant narratives.",
    institutionalRewrite: "Third-party materials are treated as external references requiring direct validation.",
    requiredEvidence: ["Relationship documentation", "Provider status letter"],
    currentSystemModule: "source-map",
    nextSteps: ["Document relationship scope", "Flag external dependency risk"],
    blockedConditions: ["No direct contractual evidence"],
  },
  {
    id: "ECO-HUMANITARIAN",
    title: "Humanitarian / Community Use Cases",
    legacyDescription: "Community and impact language used for adoption and mission narratives.",
    institutionalRewrite: "Impact narratives require measurable methodology, governance controls, and reporting.",
    requiredEvidence: ["Impact framework", "Program-level reporting"],
    currentSystemModule: "insights-and-disclosures",
    nextSteps: ["Define metrics", "Attach evidence references"],
    blockedConditions: ["No measurable impact evidence"],
  },
  {
    id: "ECO-CONTROL-PLANE",
    title: "Institutional Control Plane",
    legacyDescription: "Not part of early narrative; introduced during institutional transition.",
    institutionalRewrite: "Control-plane governance centralizes approvals, readiness checks, and release-gate discipline.",
    requiredEvidence: ["Audit logs", "Role controls", "Approval workflow traces"],
    currentSystemModule: "admin-control-plane",
    nextSteps: ["Finalize operator controls", "Expand observability"],
    blockedConditions: ["Gate failures", "Role control gaps"],
  },
  {
    id: "ECO-CLIENT-PORTAL",
    title: "Client Portal",
    legacyDescription: "Legacy public audience channels were broad and promotional.",
    institutionalRewrite: "Client portal provides role-aware evidence access and readiness tracking.",
    requiredEvidence: ["Access policy", "Disclosure templates"],
    currentSystemModule: "client-portal",
    nextSteps: ["Expand portal modules", "Align with diligence workflows"],
    blockedConditions: ["Missing access approvals"],
  },
  {
    id: "ECO-XRPL-SIM",
    title: "XRPL / AMM / DEX Simulation Layer",
    legacyDescription: "Exchange and liquidity narratives were broad and aspirational.",
    institutionalRewrite: "XRPL, AMM, and DEX logic is simulation-first and readiness-gated.",
    requiredEvidence: ["Simulation logs", "Risk review", "Provider/legal gate status"],
    currentSystemModule: "xrpl-simulation",
    nextSteps: ["Expand scenario coverage", "Add route risk scoring"],
    blockedConditions: ["No live signing approval"],
  },
  {
    id: "ECO-AI-RAG",
    title: "AI Search / Agentic RAG / MCP Future",
    legacyDescription: "Legacy content not consistently machine-readable.",
    institutionalRewrite: "Source-aware AI stack publishes claim-linked, compliance-aware, machine-readable trust artifacts.",
    requiredEvidence: ["Source map integrity", "Prompt and policy controls"],
    currentSystemModule: "ai-search-and-rag",
    nextSteps: ["Expand provenance metadata", "Strengthen policy gates"],
    blockedConditions: ["Missing source traceability"],
  },
  {
    id: "ECO-TELECOM",
    title: "Telecom / Concierge Future",
    legacyDescription: "Support was historically ad hoc and messaging-led.",
    institutionalRewrite: "Telecom concierge is planned for controlled rollout with compliance and provider constraints.",
    requiredEvidence: ["TCPA controls", "Provider onboarding", "Consent architecture"],
    currentSystemModule: "telecom-readiness",
    nextSteps: ["Keep dry-run mode", "Complete legal/provider approvals"],
    blockedConditions: ["No live telecom activation without approval"],
  },
  {
    id: "ECO-X402",
    title: "x402 Machine-Payable Future",
    legacyDescription: "No equivalent in early Troptions narratives.",
    institutionalRewrite: "x402 readiness enables metered API/report access under legal and provider controls.",
    requiredEvidence: ["Commercial policy", "Legal classification", "Settlement controls"],
    currentSystemModule: "x402-readiness",
    nextSteps: ["Publish readiness constraints", "Define billing controls"],
    blockedConditions: ["No commercial activation without approvals"],
  },
];
