export interface Insight {
  id: string;
  slug: string;
  title: string;
  summary: string;
  category: string;
  tags: string[];
  date: string;
  readingTime: string;
  status: "published" | "draft";
}

export const INSIGHTS: Insight[] = [
  {
    id: "proof-gated-issuance",
    slug: "proof-gated-issuance",
    title: "Why Proof-Gated Issuance Changes Institutional Asset Workflows",
    summary: "Traditional asset issuance relies on document exchange and trust assumptions. Proof-gated issuance replaces trust with verification — requiring evidence of funds, custody coordination, and compliance clearance before any asset is recorded.",
    category: "infrastructure",
    tags: ["proof-of-funds", "issuance", "compliance", "workflow"],
    date: "2025-01-15",
    readingTime: "6 min",
    status: "published",
  },
  {
    id: "xrpl-settlement-readiness",
    slug: "xrpl-settlement-readiness",
    title: "XRPL Settlement Readiness: What Institutions Need to Know",
    summary: "XRPL provides atomic settlement and DEX functionality that institutional workflows can leverage. Settlement readiness means having custody coordination, compliance clearance, and operational runbooks — before any live settlement occurs.",
    category: "settlement",
    tags: ["xrpl", "settlement", "institutional", "readiness"],
    date: "2025-01-18",
    readingTime: "7 min",
    status: "published",
  },
  {
    id: "gold-digital-twin",
    slug: "gold-digital-twin",
    title: "Gold Digital Twin Infrastructure: From Bullion to On-Chain Coordination",
    summary: "A gold digital twin is a namespace record that coordinates metadata, custody references, and issuance gates for physical bullion. It does not replace custody — it adds a coordination layer above it.",
    category: "asset-classes",
    tags: ["gold", "rwa", "digital-twin", "custody"],
    date: "2025-01-20",
    readingTime: "5 min",
    status: "published",
  },
  {
    id: "sblc-compliance-workflow",
    slug: "sblc-compliance-workflow",
    title: "How SBLC Workflows Work in a Compliance-First Environment",
    summary: "Standby Letters of Credit in institutional workflows require identity verification, issuance authority confirmation, and audit trails. Troptions models SBLC workflow infrastructure without replacing licensed issuing banks.",
    category: "compliance",
    tags: ["sblc", "compliance", "banking", "workflow"],
    date: "2025-01-22",
    readingTime: "6 min",
    status: "published",
  },
  {
    id: "carbon-credit-namespace",
    slug: "carbon-credit-namespace",
    title: "Carbon Credit Namespace Infrastructure for Institutional Portfolios",
    summary: "Carbon credits require registry linkage, vintage tracking, and retirement coordination. Namespace infrastructure provides a structured way to reference carbon assets within institutional portfolio systems.",
    category: "asset-classes",
    tags: ["carbon", "esg", "namespace", "registry"],
    date: "2025-01-25",
    readingTime: "5 min",
    status: "published",
  },
  {
    id: "multi-rail-settlement",
    slug: "multi-rail-settlement",
    title: "The Multi-Rail Settlement Stack: Stablecoin, XRPL, and Banking",
    summary: "No single settlement rail handles all institutional use cases. A multi-rail stack combines stablecoin pathways, XRPL atomic settlement, and traditional banking rails — each gated to appropriate use cases and compliance requirements.",
    category: "settlement",
    tags: ["stablecoin", "xrpl", "banking", "settlement", "multi-rail"],
    date: "2025-01-28",
    readingTime: "8 min",
    status: "published",
  },
  {
    id: "custody-coordination-rwa",
    slug: "custody-coordination-rwa",
    title: "Understanding Custody Coordination in RWA Workflows",
    summary: "Real world asset workflows require custody coordination, not just custody. Coordination means tracking who holds what, in what jurisdiction, under which agreement — and surfacing that information for compliance and settlement teams.",
    category: "infrastructure",
    tags: ["custody", "rwa", "coordination", "jurisdiction"],
    date: "2025-02-01",
    readingTime: "6 min",
    status: "published",
  },
  {
    id: "proof-of-funds-tracking",
    slug: "proof-of-funds-tracking",
    title: "Proof of Funds Evidence Tracking vs. Document Fabrication",
    summary: "Proof of funds systems must track evidence without enabling fabrication. Troptions uses a gated intake model: documents are referenced, not generated. The system records receipt and routing, not authenticity claims.",
    category: "compliance",
    tags: ["proof-of-funds", "evidence", "anti-fraud", "intake"],
    date: "2025-02-05",
    readingTime: "7 min",
    status: "published",
  },
  {
    id: "energy-asset-namespace",
    slug: "energy-asset-namespace",
    title: "Energy Asset Namespace Marks and Regulatory Readiness",
    summary: "Energy assets — oil reserves, gas rights, power purchase agreements — require namespace marks that link to regulatory references, custody structures, and issuance gates before they can be represented in institutional systems.",
    category: "asset-classes",
    tags: ["energy", "oil", "namespace", "regulatory"],
    date: "2025-02-08",
    readingTime: "5 min",
    status: "published",
  },
  {
    id: "kyc-kyb-institutional",
    slug: "kyc-kyb-institutional",
    title: "KYC/KYB Workflows for Institutional Onboarding",
    summary: "Institutional onboarding requires entity-level KYB — beneficial owner identification, sanctions screening, PEP checks, and ongoing monitoring. Troptions models the workflow intake layer, not the screening engine itself.",
    category: "compliance",
    tags: ["kyc", "kyb", "onboarding", "aml", "sanctions"],
    date: "2025-02-12",
    readingTime: "6 min",
    status: "published",
  },
  {
    id: "ai-agents-institutional",
    slug: "ai-agents-institutional",
    title: "What AI Agents Can and Cannot Do in Institutional Infrastructure",
    summary: "AI agents can retrieve information, generate structured reports, simulate workflows, and route requests. They cannot approve transactions, sign documents, create financial instruments, or bypass compliance gates — by design.",
    category: "ai-agentic",
    tags: ["ai", "agents", "compliance", "limitations", "mcp"],
    date: "2025-02-15",
    readingTime: "8 min",
    status: "published",
  },
  {
    id: "x402-protocol",
    slug: "x402-protocol",
    title: "x402 Protocol: Machine-Payable APIs for Institutional AI",
    summary: "x402 enables AI agents to pay for API access atomically. For institutional data, this means proof-gated delivery — agents prove payment, receive data, and the transaction is logged. All flows are simulation-only until compliance and board approval.",
    category: "ai-agentic",
    tags: ["x402", "machine-payable", "api", "ai-agents", "protocol"],
    date: "2025-02-18",
    readingTime: "7 min",
    status: "published",
  },
  {
    id: "mcp-tool-registry",
    slug: "mcp-tool-registry",
    title: "MCP Tool Registry: Permission-Guarded AI Operations",
    summary: "Model Context Protocol tools give AI agents structured access to platform capabilities. Permission guards enforce what agents can do — retrieve is permitted, approve or issue is blocked at the protocol level.",
    category: "ai-agentic",
    tags: ["mcp", "ai", "permissions", "tools", "agentic"],
    date: "2025-02-22",
    readingTime: "6 min",
    status: "published",
  },
  {
    id: "rag-compliance-retrieval",
    slug: "rag-compliance-retrieval",
    title: "RAG-Powered Knowledge Retrieval for Compliance Workflows",
    summary: "Retrieval-Augmented Generation lets compliance teams query institutional knowledge without hallucination risk. RAG retrieves from verified document stores — policies, runbooks, compliance frameworks — and cites sources.",
    category: "ai-agentic",
    tags: ["rag", "compliance", "knowledge-retrieval", "ai"],
    date: "2025-02-25",
    readingTime: "6 min",
    status: "published",
  },
  {
    id: "telnyx-institutional-comms",
    slug: "telnyx-institutional-comms",
    title: "Telnyx Telecom Infrastructure for Institutional Communications",
    summary: "Institutional communications require consent tracking, audit logging, and compliance review before deployment. Telnyx provides the carrier layer; Troptions adds TCPA/CTIA consent management and workflow integration.",
    category: "infrastructure",
    tags: ["telecom", "telnyx", "tcpa", "ctia", "communications"],
    date: "2025-03-01",
    readingTime: "5 min",
    status: "published",
  },
  {
    id: "xrpl-amm-slippage",
    slug: "xrpl-amm-slippage",
    title: "Slippage Simulation on XRPL AMM: Institutional Modeling",
    summary: "XRPL's native AMM allows simulation of trade slippage at various pool depths. Institutional modeling uses these simulations to understand settlement costs before any live trade is executed.",
    category: "settlement",
    tags: ["xrpl", "amm", "slippage", "simulation", "trading"],
    date: "2025-03-05",
    readingTime: "7 min",
    status: "published",
  },
  {
    id: "compliance-gate-architecture",
    slug: "compliance-gate-architecture",
    title: "The Compliance Gate Architecture Behind Troptions",
    summary: "Every capability in Troptions is gated: provider gate, legal gate, compliance gate, custody gate, jurisdiction gate, board approval gate. This layered architecture prevents premature activation of sensitive functionality.",
    category: "compliance",
    tags: ["compliance", "gates", "architecture", "control-plane"],
    date: "2025-03-08",
    readingTime: "8 min",
    status: "published",
  },
  {
    id: "admin-ai-ops",
    slug: "admin-ai-ops",
    title: "Admin AI Ops: Monitoring Institutional Infrastructure with AI",
    summary: "AI-assisted operations monitoring watches gate status, proof room activity, approval queues, and compliance flags. Operators receive structured summaries, not automated actions — humans stay in the loop.",
    category: "ai-agentic",
    tags: ["admin", "ai-ops", "monitoring", "control-plane"],
    date: "2025-03-12",
    readingTime: "6 min",
    status: "published",
  },
  {
    id: "pof-to-settlement",
    slug: "pof-to-settlement",
    title: "From POF to Settlement: The End-to-End Troptions Workflow",
    summary: "The full workflow: POF intake → evidence tracking → RWA intake → compliance clearance → custody coordination → settlement readiness → XRPL simulation → approval queue → board sign-off. Each step is gated.",
    category: "infrastructure",
    tags: ["workflow", "pof", "settlement", "end-to-end"],
    date: "2025-03-15",
    readingTime: "9 min",
    status: "published",
  },
  {
    id: "oil-treasury-rwa",
    slug: "oil-treasury-rwa",
    title: "Oil and Treasury RWA Categories: Intake and Readiness",
    summary: "Oil reserves and treasury instruments represent two distinct RWA categories with different regulatory frameworks, custody requirements, and settlement pathways. Troptions models intake and readiness tracking for both.",
    category: "asset-classes",
    tags: ["oil", "treasury", "rwa", "intake", "readiness"],
    date: "2025-03-18",
    readingTime: "7 min",
    status: "published",
  },
];

export const INSIGHT_CATEGORIES = [
  { id: "infrastructure", label: "Infrastructure" },
  { id: "settlement", label: "Settlement" },
  { id: "asset-classes", label: "Asset Classes" },
  { id: "compliance", label: "Compliance" },
  { id: "ai-agentic", label: "AI & Agentic" },
];

export function getInsightBySlug(slug: string): Insight | undefined {
  return INSIGHTS.find((i) => i.slug === slug);
}

export function getInsightsByCategory(category: string): Insight[] {
  return INSIGHTS.filter((i) => i.category === category);
}

export const EDITORIAL_DISCLAIMER =
  "These insights describe institutional infrastructure concepts and workflow models. They are not legal, financial, or investment advice. Troptions provides institutional operating infrastructure subject to provider, legal, compliance, custody, jurisdiction, and board approval gates.";
